Prevent error & failure when .netrc file starts with # comment
When the netrc file started with a comment instead of "machine" it would break the script.

/netrc/index.js:57
      m[key] = value;
             ^
TypeError: Cannot set property 'github.com' of null

This fixes it.